name: Check Secrets

on: [push, pull_request]

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install git-secrets
        run: |
          sudo apt-get update
          sudo apt-get install -y git-secret

      - name: Run git-secrets
        run: git secrets --scan
